export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST'
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS'
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL'
export const CONTENT_LIST_RESET = 'CONTENT_LIST_RESET'

export const PENDING_LIST_REQUEST = 'PENDING_LIST_REQUEST'
export const PENDING_LIST_SUCCESS = 'PENDING_LIST_SUCCESS'
export const PENDING_LIST_FAIL = 'PENDING_LIST_FAIL'

export const CONTENT_DETAILS_REQUEST = 'CONTENT_DETAILS_REQUEST'
export const CONTENT_DETAILS_SUCCESS = 'CONTENT_DETAILS_SUCCESS'
export const CONTENT_DETAILS_FAIL = 'CONTENT_DETAILS_FAIL'

export const CONTENT_CREATE_REQUEST = 'CONTENT_CREATE_REQUEST'
export const CONTENT_CREATE_SUCCESS = 'CONTENT_CREATE_SUCCESS'
export const CONTENT_CREATE_FAIL = 'CONTENT_CREATE_FAIL'
export const CONTENT_CREATE_RESET = 'CONTENT_CREATE_RESET'

export const CONTENT_UPDATE_REQUEST = 'CONTENT_UPDATE_REQUEST'
export const CONTENT_UPDATE_SUCCESS = 'CONTENT_UPDATE_SUCCESS'
export const CONTENT_UPDATE_FAIL = 'CONTENT_UPDATE_FAIL'
export const CONTENT_UPDATE_RESET = 'CONTENT_UPDATE_RESET'

export const CONTENT_DELETE_REQUEST = 'CONTENT_DELETE_REQUEST'
export const CONTENT_DELETE_SUCCESS = 'CONTENT_DELETE_SUCCESS'
export const CONTENT_DELETE_FAIL = 'CONTENT_DELETE_FAIL'

export const CONTENT_ACCEPT_REQUEST = 'CONTENT_ACCEPT_REQUEST'
export const CONTENT_ACCEPT_SUCCESS = 'CONTENT_ACCEPT_SUCCESS'
export const CONTENT_ACCEPT_FAIL = 'CONTENT_ACCEPT_FAIL'
export const CONTENT_ACCEPT_RESET = 'CONTENT_ACCEPT_RESET'

export const JOIN_CLASS_REQUEST = 'JOIN_CLASS_REQUEST'
export const JOIN_CLASS_SUCCESS = 'JOIN_CLASS_SUCCESS'
export const JOIN_CLASS_FAIL = 'JOIN_CLASS_FAIL'

export const CONTENT_SUBSCRIBE_REQUEST = 'CONTENT_SUBSCRIBE_REQUEST'
export const CONTENT_SUBSCRIBE_SUCCESS = 'CONTENT_SUBSCRIBE_SUCCESS'
export const CONTENT_SUBSCRIBE_FAIL = 'CONTENT_SUBSCRIBE_FAIL'
export const CONTENT_SUBSCRIBE_RESET = 'CONTENT_SUBSCRIBE_RESET'

export const CONTENT_LIKE_REQUEST = 'CONTENT_LIKE_REQUEST'
export const CONTENT_LIKE_SUCCESS = 'CONTENT_LIKE_SUCCESS'
export const CONTENT_LIKE_FAIL = 'CONTENT_LIKE_FAIL'
export const CONTENT_LIKE_RESET = 'CONTENT_LIKE_RESET'

export const CONTENT_PAY_REQUEST = 'CONTENT_PAY_REQUEST'
export const CONTENT_PAY_SUCCESS = 'CONTENT_PAY_SUCCESS'
export const CONTENT_PAY_FAIL = 'CONTENT_PAY_FAIL'
export const CONTENT_PAY_RESET = 'CONTENT_PAY_RESET'

export const CONTENT_UP_REQUEST = 'CONTENT_UP_REQUEST'
export const CONTENT_UP_SUCCESS = 'CONTENT_UP_SUCCESS'
export const CONTENT_UP_FAIL = 'CONTENT_UP_FAIL'
export const CONTENT_UP_RESET = 'CONTENT_UP_RESET'

export const CONTENT_DOWN_REQUEST = 'CONTENT_DOWN_REQUEST'
export const CONTENT_DOWN_SUCCESS = 'CONTENT_DOWN_SUCCESS'
export const CONTENT_DOWN_FAIL = 'CONTENT_DOWN_FAIL'
export const CONTENT_DOWN_RESET = 'CONTENT_DOWN_RESET'

export const CONTENT_ADD_REQUEST = 'CONTENT_ADD_REQUEST'
export const CONTENT_ADD_SUCCESS = 'CONTENT_ADD_SUCCESS'
export const CONTENT_ADD_FAIL = 'CONTENT_ADD_FAIL'
export const CONTENT_ADD_RESET = 'CONTENT_ADD_RESET'
