export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'

export const MYCOURSE_LIST_REQUEST = 'MYCOURSE_LIST_REQUEST'
export const MYCOURSE_LIST_SUCCESS = 'MYCOURSE_LIST_SUCCESS'
export const MYCOURSE_LIST_FAIL = 'MYCOURSE_LIST_FAIL'
export const MYCOURSE_LIST_RESET = 'COURSE_DETAILS_RESET'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'
export const COURSE_DETAILS_RESET = 'COURSE_DETAILS_RESET'

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST'
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS'
export const COURSE_DELETE_FAIL = 'COURSE_DELETE_FAIL'

export const CCONTENT_DELETE_REQUEST = 'CCONTENT_DELETE_REQUEST'
export const CCONTENT_DELETE_SUCCESS = 'CCONTENT_DELETE_SUCCESS'
export const CCONTENT_DELETE_FAIL = 'CCONTENT_DELETE_FAIL'
export const CCONTENT_DELETE_RESET = 'CCONTENT_DELETE_RESET'

export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST'
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS'
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL'
export const COURSE_CREATE_RESET = 'COURSE_CREATE_RESET'

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST'
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS'
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL'
export const COURSE_UPDATE_RESET = 'COURSE_UPDATE_RESET'

export const COURSE_CREATE_REVIEW_REQUEST = 'COURSE_CREATE_REVIEW_REQUEST'
export const COURSE_CREATE_REVIEW_SUCCESS = 'COURSE_CREATE_REVIEW_SUCCESS'
export const COURSE_CREATE_REVIEW_FAIL = 'COURSE_CREATE_REVIEW_FAIL'
export const COURSE_CREATE_REVIEW_RESET = 'COURSE_CREATE_REVIEW_RESET'

export const COURSE_ACCEPT_REQUEST = 'COURSE_ACCEPT_REQUEST'
export const COURSE_ACCEPT_SUCCESS = 'COURSE_ACCEPT_SUCCESS'
export const COURSE_ACCEPT_FAIL = 'COURSE_ACCEPT_FAIL'
export const COURSE_ACCEPT_RESET = 'COURSE_ACCEPT_RESET'

export const COURSE_TOP_REQUEST = 'COURSE_TOP_REQUEST'
export const COURSE_TOP_SUCCESS = 'COURSE_TOP_SUCCESS'
export const COURSE_TOP_FAIL = 'COURSE_TOP_FAIL'

export const COURSE_CONTENT_REQUEST = 'COURSE_CONTENT_REQUEST'
export const COURSE_CONTENT_SUCCESS = 'COURSE_CONTENT_SUCCESS'
export const COURSE_CONTENT_FAIL = 'COURSE_CONTENT_FAIL'

export const COURSE_LIKE_REQUEST = 'COURSE_LIKE_REQUEST'
export const COURSE_LIKE_SUCCESS = 'COURSE_LIKE_SUCCESS'
export const COURSE_LIKE_FAIL = 'COURSE_LIKE_FAIL'
export const COURSE_LIKE_RESET = 'COURSE_LIKE_RESET'

export const COURSE_NOTIFY_REQUEST = 'COURSE_NOTIFY_REQUEST'
export const COURSE_NOTIFY_SUCCESS = 'COURSE_NOTIFY_SUCCESS'
export const COURSE_NOTIFY_FAIL = 'COURSE_NOTIFY_FAIL'
export const COURSE_NOTIFY_RESET = 'COURSE_NOTIFY_RESET'