export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL'
export const STUDENT_DETAILS_RESET = 'STUDENT_DETAILS_RESET'

export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST'
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS'
export const STUDENT_LIST_FAIL = 'STUDENT_LIST_FAIL'
export const STUDENT_LIST_RESET = 'STUDENT_LIST_RESET'

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'
export const STUDENT_UPDATE_RESET = 'STUDENT_UPDATE_RESET'

export const SCONTENT_LIST_REQUEST = 'SCONTENT_LIST_REQUEST'
export const SCONTENT_LIST_SUCCESS = 'SCONTENT_LIST_SUCCESS'
export const SCONTENT_LIST_FAIL = 'SCONTENT_LIST_FAIL'

export const SCONTENT_DETAILS_REQUEST = 'SCONTENT_DETAILS_REQUEST'
export const SCONTENT_DETAILS_SUCCESS = 'SCONTENT_DETAILS_SUCCESS'
export const SCONTENT_DETAILS_FAIL = 'SCONTENT_DETAILS_FAIL'
export const SCONTENT_DETAILS_RESET = 'SCONTENT_DETAILS_RESET'

export const SCONTENT_CREATE_REQUEST = 'SCONTENT_CREATE_REQUEST'
export const SCONTENT_CREATE_SUCCESS = 'SCONTENT_CREATE_SUCCESS'
export const SCONTENT_CREATE_FAIL = 'SCONTENT_CREATE_FAIL'
export const SCONTENT_CREATE_RESET = 'SCONTENT_CREATE_RESET'

export const SCONTENT_UPDATE_REQUEST = 'SCONTENT_UPDATE_REQUEST'
export const SCONTENT_UPDATE_SUCCESS = 'SCONTENT_UPDATE_SUCCESS'
export const SCONTENT_UPDATE_FAIL = 'SCONTENT_UPDATE_FAIL'
export const SCONTENT_UPDATE_RESET = 'SCONTENT_UPDATE_RESET'

export const SCONTENT_DELETE_REQUEST = 'SCONTENT_DELETE_REQUEST'
export const SCONTENT_DELETE_SUCCESS = 'SCONTENT_DELETE_SUCCESS'
export const SCONTENT_DELETE_FAIL = 'SCONTENT_DELETE_FAIL'
