export const TCOURSE_LIST_REQUEST = 'TCOURSE_LIST_REQUEST'
export const TCOURSE_LIST_SUCCESS = 'TCOURSE_LIST_SUCCESS'
export const TCOURSE_LIST_FAIL = 'TCOURSE_LIST_FAIL'

export const TCOURSE_DETAILS_REQUEST = 'TCOURSE_DETAILS_REQUEST'
export const TCOURSE_DETAILS_SUCCESS = 'TCOURSE_DETAILS_SUCCESS'
export const TCOURSE_DETAILS_FAIL = 'TCOURSE_DETAILS_FAIL'

export const TCOURSE_DELETE_REQUEST = 'TCOURSE_DELETE_REQUEST'
export const TCOURSE_DELETE_SUCCESS = 'TCOURSE_DELETE_SUCCESS'
export const TCOURSE_DELETE_FAIL = 'TCOURSE_DELETE_FAIL'

export const TCOURSE_UPDATE_REQUEST = 'TCOURSE_UPDATE_REQUEST'
export const TCOURSE_UPDATE_SUCCESS = 'TCOURSE_UPDATE_SUCCESS'
export const TCOURSE_UPDATE_FAIL = 'TCOURSE_UPDATE_FAIL'
export const TCOURSE_UPDATE_RESET = 'TCOURSE_UPDATE_RESET'
